[package]
name = "budget-to-csv"
version = "0.1.1"
edition = "2024"

[dependencies]
regex = "1.11.1"

[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
